version: "3"
services:
  ganai:
    image: gan-ai:latest
    runtime: nvidia
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gan-ai
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      PYTHONUNBUFFERED: 1
      WOR_ADDR: 0
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
        limits:
          memory: "6g"
          cpus: '0.5'
    ports:
      - 1234:1234

